kernelci/kernelci-project

kernelci.org/content/docs/_index.md, kernelci.org/content/docs/labs/_index.md, kernelci.org/content/docs/labs/lava.md, kernelci.org/content/docs/tests/_index.md, kernelci.org/content/docs/tests/howto.md, kernelci.org/content/docs/tests/test-suites.md, kernelci.org/content/docs/workflow/_index.md, kernelci.org/content/docs/workflow/staging.md
Add initial documentation with general files copied from `kernelci-core`.
See also: https://github.com/kernelci/kernelci-core/pull/608
=> T26417 initial documentation

kernelci.org/content/en/docs/builds/_index.md, kernelci.org/content/en/docs/builds/builds.md
Mostly ported over from the wiki with a little editing.
Signed-off-by: Mark Brown <broonie@kernel.org>
=> kernelci.org: Add build configuration documentation

kernelci.org/content/en/docs/bisection/_index.md, kernelci.org/content/en/docs/bisection/bisection.md
Ported over from the wiki.
Signed-off-by: Mark Brown <broonie@kernel.org>
=> kernelci.org: Add bisection documentation

kernelci.org/content/en/docs/team/tsc.md
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
=> Docs: add section for lava-docker

kernelci.org/content/en/docs/bisection.md
Move content from the old wiki: https://github.com/kernelci/kernelci-doc/wiki/
=> Move content from old wiki

kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/org/tsc.md
=> Update links for cip instance

kernelci.org/content/en/docs/org/_index.md, kernelci.org/content/en/docs/org/board.md, kernelci.org/content/en/docs/org/members.md
First PR towards resolving #43
=> Port content from foundation site to static docs site

kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/instances/staging.md, kernelci.org/content/en/docs/labs/lava.md
Signed-off-by: lakshmipathi.ganapathi <lakshmipathi.ganapathi@collabora.com>
=> docs: Fix broken links in the documents

.gitmodules, kernelci.org/content/en/docs/kcidb
Embed the reorganized KCIDB documentation.
Concerns kernelci/kcidb#213
=> kernelci.org: Add KCIDB docs

kernelci.org/content/en/docs/instances/chromeos.md, kernelci.org/content/en/docs/instances/cip.md, kernelci.org/content/en/docs/instances/production.md, kernelci.org/content/en/docs/instances/staging.md
Update the page about the ChromeOS instance with an intro paragraph and some rewording.
=> docs: update ChromeOS instance page

kernelci.org/content/en/docs/org/maintainers.md, kernelci.org/content/en/docs/org/working-groups.md
- Add Denys to Sysadmin workgroup  members list
- Fix typos in mgalka username in several places.
=> Update Sysadmin workgroup members list. Fix typos in mgalka username

kernelci.org/content/en/docs/architecture.md
relative link results in 404.  fully qualified via https://
=> updated link

kernelci.org/content/en/docs/org/tsc/votes.md
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
=> TSC/votes: Add vote from TSC Monthly 2022-12-08

kernelci.org/content/en/docs/org/tsc/votes.md
Add TSC voting records for 2023-01-12 and fix typos in the nicknames.
=> TSC voting records 2023-01-12

kernelci.org/content/en/docs/contrib.md
Add a few guidelines about filing PRs agains kernelci-core.
Signed-off-by: Michal Galka <michal.galka@collabora.com>
=> docs: Add contributing guidelines

kernelci.org/content/en/docs/org/tsc/_index.md, kernelci.org/content/en/docs/org/tsc/votes.md
Add voting records from the TSC monthly meeting on 2023-03-09 and remove Alex from the list of TSC members accordingly.
=> TSC 2023-03-09

kernelci.org/content/en/docs/org/maintainers.md, kernelci.org/content/en/docs/org/tsc/votes.md
Update the TSC voting records and add Jeny to the list of `kernelci-core` maintainers.
=> TSC update

kernelci.org/content/en/docs/admin/_index.md
Update the landing page of the admin section accordingly to the fact that we're now focusing on the new API rather than the legacy system.
=> kernelci.org: update admin section summary

kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
As R116 builds completed and being tested we need to update documentation.
=> kernelci.org: Add R116 entries

kernelci.org/content/en/docs/org/tsc/_index.md, kernelci.org/content/en/docs/org/working-groups.md
As discussed with Michał, update his email address with gmail.com.
=> kernelci.org: update mgalka's email address

kernelci.org/content/en/docs/org/tsc/votes.md
Add a TSC voting record for the 2023-12-14 monthly.
=> kernelci.org: add TSC voting record for 2023-12-14

kernelci.org/content/en/docs/org/tsc/_index.md, kernelci.org/content/en/docs/org/tsc/votes.md
Add a TSC voting record for the monthly meeting on 2024-02-08 and add Paweł to the list of TSC members accordingly.
=> TSC update 2024-02-08

kernelci.org/content/en/blog/posts/2024/tsc-updates/index.md
Replicate on the blog the message we sent to the mailing list.
=> kernelci.org: add blog post about TSC updates

.github/workflows/deploy.yml
Fix indentation error caused by copy-paste at last moment.
=> workflows/deploy: Fix indentation in yaml

.github/workflows/deploy.yml
We might need to retrigger staging by adding one more comment.
=> workflows/deploy: Trigger also on issue_comment edit

.github/workflows/deploy.yml
It is hard to verify workflows locally, so many small PR is happening, sorry.
=> workflows/deploy: Fix if condition

.github/workflows/deploy.yml
Finally spotted issue. - vs _ :(
=> workflows/deploy: Fix strip_components

.github/workflows/deploy.yml
=> workflows/deploy: Checkout correct commit

.github/workflows/deploy.yml
By some reason condition is triggering on all issues comments.
=> workflows: Condition still not working, attempt to fix

.github/workflows/deploy.yml
Workflow logic and YAML is not well documented, and leave a lot of places where it is possible to make a mistake
=> workflows: Fix if condition worflow logic, finally tested

.github/workflows/deploy.yml
As seems restriction by team doesnt work, use allowed username list (temporary, to be improved). Additionally, make option to run workflow manually.
=> workflows: Add manual run and restrict by usernames

.github/workflows/deploy.yml
Also fix AND/OR logic as workflow is still triggered on issues (not PR).
=> workflows: Remove braces, as they are not usable in this example

kernelci.org/content/en/docs/org/tsc/votes.md
Record votes for "Cleanup admin permissions" motion.
=> kernelci.org: add TSC voting record for 2024-05-13

.github/workflows/deploy.yml
1)npm cache failed during recent deploy, temporary disable it, until more time available to check why it is needed at all. 2)Add submodules update step
=> workflows: Disable npm caching and update submodules

.github/ISSUE_TEMPLATE/api-early-access.md
Update `kci` commands in the template for creating GH issue for user account request.
=> .github/ISSUE_TEMPLATE: update `api-early-access` template

.github/workflows/deploy.yml
scp, as expected wont remove old files, use rsync+ssh as it is more appropriate for this job.
=> workflows: Use rsync instead of scp

.github/workflows/deploy.yml
Add variant for production deployment.
=> workflows: Add production deployment

.github/workflows/deploy.yml
We need to execute few more staging-specific steps on issue_comment
=> workflows: Add staging steps on issue_comment

.github/workflows/deploy.yml
As per discussion, we allow @patersonc in workflow to deploy website.
=> workflows: Add patersonc to allow list of website deploy

kernelci.org/assets/scss/_variables_project.scss
Make it KernelCI colors :)
No rush to merge this. We can complete the DNS change first.
=> docs: update style colors to match branding

.github/workflows/deploy.yml
Deploy website automatically if anything merged into main branch.
=> workflows: Add deploy on main branch merge

kernelci.org/content/en/org/tsc/votes.md
Record the votes concluded on 2024-06-21.
=> Record 2024-06-21 TSC votes

kernelci.org/content/en/org/tsc/votes.md
Record the votes concluded on 2024-07-11.
=> Record 2024-07-11 TSC votes

kernelci.org/content/en/org/tsc/votes.md
Record the votes concluded on 2024-08-13.
=> Record 2024-08-13 TSC votes

kernelci.org/config.toml
We should also add a note on the dashboard many parts of it are still under development, but we are already able to add value to some users (and get feedback from them). So let's show it.
=> docs: add the new Web Dashboard to the menu

kernelci.org/content/en/kernel-community/_index.md, kernelci.org/content/en/kernel-community/view-results.md
Basic page to list our current was to interact with tests results.
=> Add documentation about vizualizing the results

kernelci.org/content/en/org/tsc/votes.md
MOTION: Add Paweł Wieczorek to the sysadmin working group
=> votes.md: Add voting records for motion at #2024-09-05

kernelci.org/content/en/org/tsc/votes.md
Record the votes concluded on 2024-10-31.
=> Record 2024-10-31 TSC votes

kernelci.org/content/en/org/tsc/votes.md
=> Record 2024-11-12 votes

.github/workflows/deploy.yml
To write into PR comments i need additional permission
=> fix(deploy.yml): Add permissions

kernelci.org/content/en/org/maintainers.md, kernelci.org/content/en/org/members.md, kernelci.org/content/en/org/working-groups.md
After notificng that last edit date doesn't match on some documents, i noticed small grammar/spelling mistakes, links to non-existing documents, etc.
=> fix(org/*): Multiple minor fixes and spotted mistakes

kernelci.org/content/en/org/lfx.md
Marking as draft meanwhile we wait the change to happen at LFX
=> docs: lfx: add logspec repo to the list

kernelci.org/content/en/org/tsc/votes.md
Add motion: Archiving legacy or inactive repositories
=> (votes.md) Update TSC voting / motion records

kernelci.org/content/en/architecture/_index.md
A couple of improvements I noticed during reviewing https://github.com/kernelci/kernelci-project/pull/517/.
=> Minor improvements to KernelCI architecture documentation

kernelci.org/content/en/faq.md
Some fixes to outdated information and add a new question about how to add platforms to test.
=> docs: small updates to the FAQ session

kernelci.org/content/en/components/_index.md, kernelci.org/content/en/contacts.md, kernelci.org/content/en/faq.md, kernelci.org/content/en/intro/_index.md, kernelci.org/content/en/org/_index.md, kernelci.org/content/en/tests/_index.md
Put the sections in a more logical order.
=> docs: reorder side menu
