kernelci.org/content/docs/team/_index.md, kernelci.org/content/docs/team/board.md, kernelci.org/content/docs/team/tsc.md
Add descriptions of all the roles handled by the TSC team as previously discussed.  This will need to evolve and be refined, but it should already provide a good enough starting point.
=> T26035 TSC roles

kernelci.org/config.toml
Add the branch name and sub-directory settings to config.toml.  This
fixes the handy links used in the Documentation section to directly
edit or add pages on the GitHub web UI.
=> kernelci.org: update GitHub branch and directory in config.toml

kernelci.org/content/en/_index.html
The KCIDB Grafana dashboard is now hosted on kcidb.kernelci.org rather
than the temporary port 3000.  Update the link URL accordingly.
=> kernelci.org: replace KCIDB url with kcidb.kernelci.org

.gitattributes, kernelci.org/content/en/about/_index.html, kernelci.org/content/en/about/background.jpeg
Add an "About" section with static content moved from the dashboard
pages "sponsors" and "contact".
=> kernelci.org: add About section

kernelci.org/content/en/docs/faq.md
Add an FAQ page to the Documentation section.  The content is taken
from various places, edited and extended with typical questions that
are relevant with today's status of KernelCI.
=> kernelci.org: add FAQ page in Documentation

kernelci.org/config.toml, kernelci.org/content/en/_index.html, kernelci.org/content/en/docs/team/tsc.md
Update the web dashboard URLs to point to linux.kernelci.org as the
static website is being deployed on kernelci.org.
=> kernelci.org: change dashboard URL to linux.kernelci.org

.gitattributes, kernelci.org/.gitattributes
Move git-lfs meta-data for the `baground.png` for the About section to `kernelci.org/.gitattributes` to keep it self-contained.
=> git cleanup

README.md, kernelci.org/content/en/docs/admin/_index.md, kernelci.org/content/en/docs/admin/secrets.md
Add admin documentation section with "secrets" page about encrypted files.
=> T26036 git crypt readme

kernelci.org/content/en/docs/tests/howto.md
This pull request improves documentation by updating some paths that changed.
=> Rename all references from 'jenkins/debian' to 'config/rootfs'

kernelci.org/content/en/docs/team/tsc.md
Add a section for the Chrome OS KernelCI instance to the TSC documentation page with designated maintainers.  Update the sections for the staging and production instances as well to keep the format consistent.
=> Docs: add section for Chrome OS instance

kernelci.org/content/en/docs/tests/test-suites.md
add kselftest section in native tests page.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>
=> kernelci.org: Include a kselftest section

kernelci.org/content/en/docs/team/tsc.md
I will be involved with 
- kernelci-core
- testing
- setting up and maintaining the cip.kernelci.org instance
- lava-docker
=> kernelci.org: Add alicef as TSC member

kernelci.org/content/en/docs/team/tsc.md
Add a section for the CIP instance to the TSC documentation page with designated maintainers.
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
=>  Docs: add section for CIP instance

kernelci.org/content/en/about/_index.html
We've moved away from Freenode. Update static website accordingly.
=> IRC channel has moved to libera.chat

kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/instances/staging.md
Update the page about the staging instance to align it with the
current state of things.
=> kernelci.org: update docs for the staging instance

kernelci.org/content/en/docs/tests/kselftest.md
The Pine H64 board is failing to run kselftest in Collabora's LAVA
lab, so drop it from the summary table in the docs.
=> kernelci.org: drop Pine H64 from kselftest summary table

kernelci.org/content/en/docs/instances/production.md
Add a page about the production instance on linux.kernelci.org with a
quick introduction and steps to do the weekly update.
=> kernelci.org: add page about the production instance

kernelci.org/content/en/docs/labs/lava.md, kernelci.org/content/en/docs/tests/howto.md
Update the How-To guide to add new KernelCI native tests using a
simple example based on uname.  This goes through the prototyping
steps without building a new rootfs image, by installing things at
runtime using NFS root.
=> kernelci.org: update How-To with uname example

kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/team/_index.md, kernelci.org/content/en/docs/tests/_index.md, kernelci.org/content/en/docs/tests/kselftest.md, kernelci.org/content/en/docs/tests/ltp.md
Add Hugo weight attributes to a number of sections and pages in the
documentation to sort them in the index.
=> kernelci.org: add Hugo weight attributes in documentation

kernelci.org/content/en/_index.html
Copy the paragraph and kernelci-members email button from
https://foundation.kernelci.org/ as an interim solution until the
foundation.kernelci.org content gets merged with the kernelci.org
static site.
Suggested-by: Guy Lunardi <guy.lunardi@collabora.com>
=> kernelci.org: add paragraph with kernelci-members email button

kernelci.org/content/en/docs/team/board.md
Some information still needs adding for the members, and the list may not be complete.
=> kernelci.org: Add advisory board members

kernelci.org/.gitattributes, kernelci.org/config.toml, kernelci.org/content/en/docs/architecture.md, kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/team/_index.md, kernelci.org/static/image/kernelci-bigger-picture.png
Add a documentation page with an overview of the KernelCI architecture, including the "bigger picture" image and use the [Mermaid](https://mermaid-js.github.io/) library to make diagrams in Markdown.
=> T29625 Add architecture documentation

kernelci.org/content/en/docs/instances/local.md
Add page that gives a quick guide to setup a local instance of KernelCI
for development.
=> Add instructions for setting up local KernelCI

README.md, kernelci.org/content/en/about/_index.html
Add more content from the current https://foundation.kernelci.org/ website as part of https://github.com/kernelci/kernelci-project/issues/43.
=> Add more information about the project to the about pages

kernelci.org/content/en/docs/org/members.md
Add "Join Now" link to main navigation
Should be viewable on all https://static.staging.kernelci.org/about/ pages when picked up.
Part of https://github.com/kernelci/kernelci-project/issues/43
=> Add "Join Now" link to main navigation

kernelci.org/content/en/blog/posts/2021/.gitattributes, kernelci.org/content/en/blog/posts/2021/hackfests.md, kernelci.org/content/en/blog/posts/2021/hackfests/hackfest-2-screenshot-2021-09-08-cropped.png, kernelci.org/content/en/blog/posts/2021/hackfests/index.md
Add a blog post about KernelCI hackfests and how they help grow the
ecosystem around upstream kernel testing as well as a summary of the
first 2 hackfests.
=> kernelci.org: Add blog post about hackfests

.github/ISSUE_TEMPLATE/kernel-bug.md
Add a GitHub issue template for kernel bugs, to keep track on the workboard: https://github.com/orgs/kernelci/projects/6
=> Add template for kernel bugs

.gitattributes, kernelci.org/static/image/kernelci-horizontal-color.png
Add the KernelCI logo as a static file so it can be used in various
places including README files for the trade mark application.
=> kernelci.org: add image/kernelci-horizontal-color.png

kernelci.org/content/en/docs/org/tsc.md
Add gtucker and spbnick as maintainers for Slack on the TSC org page.
=> kernelci.org: add Slack maintainers on TSC page

kernelci.org/content/en/docs/instances/production.md
Add the "Known issues" section to the production instance page with a
description of scheduler settings that need to be added manually after
the update.
=> kernelci.org: Add "Known issues" section to the production page

kernelci.org/content/en/docs/org/tsc.md
Remove Laks from the list of TSC members as he will not be available
to fulfil this role in the foreseeable future.
=> kernelci.org: remove Laks from TSC members

kernelci.org/content/en/docs/org/_index.md, kernelci.org/content/en/docs/org/board.md, kernelci.org/content/en/docs/org/tsc.md, kernelci.org/content/en/docs/org/working-groups.md
Add a page in the Organization section about working groups, with Web Dashboard and Sysadmin to start with.
=> Add working groups

kernelci.org/content/en/docs/instances/staging.md
Improve the staging documentation by fixing the kernel branch names and documenting the 3 possible trees being used.
Replaces #109
=> kernelci.org docs: fix staging kernel branch names

kernelci.org/content/en/docs/instances/production.md
Tweak the documentation about production update procedure to set the
monitor timer to 1h rather than 2h.  Some recent rework means the
build trigger jobs won't pile up in the queue if the monitor is run
more often.
=> kernelci.org: docs: change monitor job timer to 1h

README.md, kernelci.org/docker-compose.yaml
Add a basic `docker-compose.yaml` file to start the local development server with all parameters and volumes already defined.
=> Add docker-compose.yaml

.gitattributes, kernelci.org/content/en/blog/posts/2022/rfp-sysadmin/RFP-Sysadmin-Maintenance-2022-v3.pdf, kernelci.org/content/en/blog/posts/2022/rfp-sysadmin/index.md
Add a small blog post to introduce the Sysadmin Maintenance 2022 RFP with a link to the PDF hosted directly on the website.
=> kernelci.org: add blog post about sysadmin RFP

kernelci.org/content/en/docs/_index.md, kernelci.org/content/en/docs/admin/_index.md, kernelci.org/content/en/docs/admin/secrets.md, kernelci.org/content/en/docs/architecture.md, kernelci.org/content/en/docs/bisection.md, kernelci.org/content/en/docs/faq.md, kernelci.org/content/en/docs/instances/_index.md, kernelci.org/content/en/docs/instances/local.md, kernelci.org/content/en/docs/instances/production.md, kernelci.org/content/en/docs/instances/staging.md, kernelci.org/content/en/docs/labs/_index.md, kernelci.org/content/en/docs/labs/lava.md, kernelci.org/content/en/docs/org/_index.md, kernelci.org/content/en/docs/org/board.md, kernelci.org/content/en/docs/org/members.md, kernelci.org/content/en/docs/org/tsc.md, kernelci.org/content/en/docs/tests/_index.md, kernelci.org/content/en/docs/tests/howto.md, kernelci.org/content/en/docs/tests/kselftest.md, kernelci.org/content/en/docs/tests/ltp.md
Drop the draft attribute as it's not used for anything and pages
randomly had it set to true or false.
=> doc: drop draft attribute

kernelci.org/content/en/docs/admin/secrets.md
Tweak the sample command to send a GPG key to a key server as the key
hash should be provided.
=> kernelci.org: docs: tweak GPG key sample command

kernelci.org/content/en/docs/org/tsc.md
Add Denys Fedoryshchenko to the TSC members list.
=> kernelci.org: docs: add Denys to the TSC members

kernelci.org/content/en/docs/org/tsc.md
Fix the typo: s/kerlci/kernelci/.
Signed-off-by: Tzung-Bi Shih <tzungbi@kernel.org>
=> kernelci.org: fix typo in TSC page

kernelci.org/content/en/docs/instances/cip.md
Add documentation for the CIP instance
=> kernelci.org: Add documentation for the CIP instance

kernelci.org/content/en/docs/org/working-groups.md
Add Vince Hillier to the list of members of the sysadmin working group.
=> kernelci.org: add Vince to the Sysadmin Working Group

kernelci.org/content/en/blog/posts/2022/sysadmin-onboard/index.md
Fix typos in Vince Hillier's name as well as a few other glitches in the blog post about our new SysAdmin.  Use full URIs for relative links so they work regardless of the current blog URL and add some links to the TSC and instances documentation pages.
Fixes: 3f66b646a770 ("blog: add post to announce new SysAdmin")
=> kernelci.org: fix typos in sysadmin blog post

kernelci.org/content/en/docs/org/tsc.md
Add a section to detail the TSC rules in terms of votes and members. This is based on the project charter document and adds more context as to how this should work in practice.
A sub-section should be created as a follow-up to archive the results of all the votes carried out by the TSC.
=> kernelci.org: tsc: add section about TSC rules

kernelci.org/content/en/about/_index.html, kernelci.org/content/en/blog/posts/2020/05/11/index.html, kernelci.org/content/en/blog/posts/2020/07/09/index.html, kernelci.org/content/en/blog/posts/2020/08/21/index.html, kernelci.org/content/en/docs/org/tsc.md, kernelci.org/content/en/logo/_index.html
Update all links to the mailing list to point to the new one kernelci@lists.linux.dev and all references to the `#kernelci` IRC channel on libera.chat rather than Freenode.
=> Update mailing list address and IRC network references

kernelci.org/content/en/docs/org/tsc.md
Update the TSC rules based on previous discussions to clarify the following points:
* decisions that always require a TSC vote
* quotes from the LF project charter about consensus and votes
* what is expected from active TSC members
=> kernelci.org: update TSC rules based on previous discussions

kernelci.org/content/en/docs/org/working-groups.md
Add a list of the admin rights given to the members of the SysAdmin working group as per the 2022-12-08 TSC vote.
=> kernelci.org: add list of SysAdmin rights

kernelci.org/content/en/docs/org/working-groups.md
We haven't marked the lead in the first version of this doc. Doing it now.
Signed-off-by: Gustavo Padovan <gustavo.padovan@collabora.com>
=> Working Groups: add lead to the Web Dashboard WG

kernelci.org/content/en/docs/admin/secrets.md
Add a paragraph about how to contribute to the encrypted files in the repository such as `passwords.toml`.
=> kernelci.org: docs: add note about contributing to encrypted files

kernelci.org/content/en/docs/org/working-groups.md
Marking the lead of the SysAdmin Working Group.
We need a person who'll be officially responsible for maintaining the SysAdmin Work Group board and keeping track of priorities and progress on the tasks.
=> Working Groups: add lead to the SysAdmin WG.

kernelci.org/content/en/docs/instances/chromeos/_index.md
When making the chromeos instance doc a subsection I forgot to update the link pointing to the changelog.
Fixes: https://github.com/kernelci/kernelci-core/issues/1846
=> docs: chromeos: fix changelog link

.github/ISSUE_TEMPLATE/user-story.md
Add an issue template for creating user stories for the User Experience workboard.
=> GitHub: add issue template for user stories

kernelci.org/content/en/docs/instances/chromeos/chromeos_changelog.md
This is the documentation counterpart of the kernelci-core PR: 
https://github.com/kernelci/kernelci-core/pull/1832
We need to wait until the kernelci-core PR lands and we have images on public storage before landing this (I will update the TODO: add link).
=> chromeos_changelog: add cherry & asurada/jacuzzi kernel uprev docs

kernelci.org/content/en/blog/.gitattributes, kernelci.org/content/en/blog/posts/2023/rfp-ux-analysis/RFP-UX-Analysis-2023-v2.pdf, kernelci.org/content/en/blog/posts/2023/rfp-ux-analysis/index.md
Add the PDF file with the UX Analysis RFP and a blog post with a link and description.
Note: The date will need to be updated to `2023-05-29` before merging.  The current date is to be able to see the blog post on the staging website first.
=> Add UX Analysis RFP document and blog post

kernelci.org/content/en/docs/org/working-groups.md
As discussed and agreed, set Denys as the new SysAdmin working goup lead.
Also consolidate a bit the format of the page and add some typical tasks that should be part of the role of a working group lead.
=> Update working groups and set Denys as sysadmin lead

kernelci.org/content/en/blog/posts/2023/rfp-ux-analysis-q-and-a/index.md
Add an extra blog post with questions and answers based on discussions collected so far with the potential vendors for the UX Analysis 2023 RFP.
=> kernelci.org: add UX Analysis Q&A blog post

kernelci.org/content/en/docs/labs/lava.md, kernelci.org/content/en/docs/tests/howto.md
As kernelci-core keep evolving we got some name changes that was missing in documentation. Renaming config files to represent new changes.
Fixes: https://github.com/kernelci/kernelci-project/issues/223
=> docs: rename lab to runtime

kernelci.org/content/en/docs/tests/_index.md
Add in a new webpage discussing ways to get a contributor's test added to other CI services easily.
Signed-off-by: Don Zickus <dzickus@redhat.com>
=> Add info about using external testsuite

kernelci.org/content/en/blog/posts/2023/api-timeline/index.md
Add a blog post to announce the overall timeline for transitioning to the new API & Pipeline.
=> kernelci.org: add blog post with API timeline

kernelci.org/content/en/docs/tests/_index.md
Remove the part of the Tests documentation section about KCIDB to add it in the KCIDB dedicated section instead.  This is to keep the Tests section only about kernel tests and not about any particular CI system.
=> kernelci.org: move KCIDB part from Tests section to KCIDB

kernelci.org/content/en/docs/org/_index.md
Bring the Organization section to the top of the table of contents by setting its weight to 1.  This provides some overview for the project so it makes sense to have there.
=> kernelci.org: bring org section to the top

.github/ISSUE_TEMPLATE/api-early-access.md
Add an issue template for requesting an Early Access account with the new API.
=> github: add API early access issue template

kernelci.org/content/en/blog/posts/2023/api-early-access/index.md
Add a blog post to kick off the new API Early Access phase.
=> kernelci.org: add blog post about API Early Access

kernelci.org/content/en/docs/admin/api.md
Add an API page to the sysadmin section about how to create an admin token and how to add users.
=> kernelci.org: add API admin page

kernelci.org/content/en/blog/posts/2023/api-timeline/index.md
Remove the link to the definition of a DAG in the API timeline blog post as the nodes form a simple tree structure which isn't really a DAG.  Nodes don't have multiple parents.
Fixes: e7e701974b9f ("kernelci.org: add blog post with API timeline")
=> kernelci.org: remove DAG reference as it's just a plain tree

kernelci.org/content/en/docs/admin/api.md
Remove the secret signature from the Azure SAS token mentioned in the documentation.  We've now decided to stop using a single public token for Early Access to remove the potential threat of users abusing it and uploading files not related to KernelCI etc.
Link: https://lore.kernel.org/kernelci/DM5PR0102MB34778BDC7668A45F8F55780180D3A@DM5PR0102MB3477.prod.exchangelabs.com/T/#u
=> kernelci.org: remove signature from Azure SAS token

kernelci.org/content/en/docs/org/_index.md
Add a section on the Organisation page about regular project meetings. This also makes it possible for anyone to join the public ones on Jitsi without requiring a calendar invitation containing all the details.
=> kernelci.org: add section about meetings under Organisation

kernelci.org/content/en/docs/admin/api.md
Update the email template for sending out API user account details to clearly show the share name as it might not always be exactly the same as the username.
=> kernelci.org: update API account email with share name

kernelci.org/content/en/docs/org/maintainers.md
As discussed with Michał, update all maintainer entries to remove his responsibilities for now due to lack of availability.
=> kernelci.org: remove mgalka from maintainers

kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
This PR contains 2 commits and needs to wait until @nuclearcat fixes the 6.6 Tast tests and also the following kernelci-core PR lands:
https://github.com/kernelci/kernelci-core/pull/2208
=> kernelci.org: legacy: chromeos: update documentation for kernels 6.6

kernelci.org/content/en/docs/org/working-groups.md
Alex has left Collabora a while ago and never participated in the project again, so we are removing her.
For future removals, we probably want to push a vote through the WG.
=> Web Dashboard WG: Remove inactive member

kernelci.org/content/en/docs/admin/api.md
Update documentation for getting admin API token and creating user accounts as per the latest changes in the API and `kci` command syntax.
=> kernelci.org: update admin documentation

kernelci.org/content/en/blog/posts/2023/ux-analysis/index.md
Add a blog post about the UX Analysis project starting now with ProFUSION following the RFP published earlier in 2023.
=> kernelci.org: add blog about UX Analysis project

kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
Replaces #276.
This depends on some other unspecified changes and things to be tested.
@nuclearcat please confirm when it's ready to be merged.
=> kernelci.org: update ChromeOS docs for v6.6 LTS

kernelci.org/content/en/docs/org/tsc/votes.md
Add a TSC voting record for the 2023-10-12 monthly which was effectively completed over email due to lack of quorum.
=> kernelci.org: add TSC voting record for 2023-10-12

kernelci.org/content/en/docs/org/maintainers.md
Add a Project section to the maintainers page for the kernelci-project repository with current maintainers (gtucker and patersonc).
=> kernelci.org: add kernelci-project maintainers section

README.md
Tweak the sample commands for setting up a local static website instance.  The git-lfs and submodule commands should be run the top-level directory while the Hugo server needs to be run from within the kernelci.org sub-directory.
Fixes: 4706e7272f79 ("README.md: add section about the kernelci.org static website")
=> README.md: fix static website sample commands

.github/ISSUE_TEMPLATE/api-early-access.md
Replace gctucker with nuclearcat as the default assignees in the template for Early Access account creation issues.
=> github: assign Early Access issues to nuclearcat

kernelci.org/content/en/docs/org/tsc/_index.md
Add a link on the TSC page to the Meetings section with the details about the TSC monthlies.
=> kernelci.org: add link to TSC meeting details

kernelci.org/content/en/docs/org/tsc/_index.md
Add a Duties section on the TSC page to clarify what TSC members are meant to be doing or responsible for.  Update the wording of the Members section accordingly.  This should be based on current proceedings and is merely about documenting them without introducing anything new.
=> kernelci.org: clarify the duties of TSC members

kernelci.org/content/en/docs/org/working-groups.md
Add info about the mailing list we just created for the Web Dashboard Working Group.
=> Web Dashboard WG: Document mailing list

kernelci.org/content/en/docs/org/board.md
Add a section on the Advisory Board page with definitions for the key roles (Chair, Treasurer, PM).  Also update the wording in the intro paragraph accordingly.
=> kernelci.org: add Advisory Board role definitions

kernelci.org/content/en/docs/org/tsc/_index.md
Add a paragraph on the TSC page to limit email votes with a 2-week window.  If no majority has been reached by then, the motion is not moved.  Also clarify a bit the wording around voting by email in general.
=> kernelci.org: add TSC 2-week window for email votes

kernelci.org/content/en/docs/org/board.md
Update the list of board members now that elections have taken place. The main change is that Don has been elected AB Chair for 2024.
=> kernelci.org: update board members list

kernelci.org/content/en/docs/legacy/instances/chromeos/_index.md
While contributing changes to ChromiumOS upstream, we noticed this part is missing from the documentation, so we add some details.
=> kernelci.org: legacy: chromeos: add CrOS contribution doc

kernelci.org/content/en/docs/org/maintainers.md
Update the Maintainers page as nuclearcat (Denys) is now an owner of the GitHub KernelCI organization, co-maintainer of kernelci-project and replaces mgalka as Docker Hub owner since we have a limited number of available "seats" with our free account.
=> kernelci.org: update Maintainers page with Denys' new roles

kernelci.org/content/en/docs/org/working-groups.md
As the RFP phase is now complete and I'm no longer going to be directly involved in the Web Dashboard activities, remove gtucker from the working group as discussed with Gustavo and others.
=> kernelci.org: remove gtucker from Web Dashboard working group

kernelci.org/content/en/docs/org/tsc/_index.md
As per the TSC vote last week, add Jeny to the list of TSC members.
=> kernelci.org: add Jeny to the list of TSC members

kernelci.org/content/en/docs/org/maintainers.md
Add Gustavo Padovan to the list of groups.io maintainers.  There hasn't been any TSC vote as this is not a change of role but only a documentation update to align it with the current state of things.
=> kernelci.org: add padovan to groups.io maintainers

kernelci.org/content/en/docs/org/maintainers.md
Add the cros-ec-tests repository to the list of components for the Native Tests feature on the Maintainers page.
=> kernelci.org: add cros-ec-tests component to Native Tests

kernelci.org/content/en/docs/legacy/how-to.md
Update the legacy How-To documentation page about how to add new LAVA tests using Debian Bullseye.  Also fix some loose ends and dead links.
Fixes #307
=> Update legacy How-To with Debian Bullseye

kernelci.org/content/en/docs/org/tsc/_index.md
Add a paragraph to clarify how to deal with abstentions, basically by not counting them as votes.
=> kernelci.org: clarify abstentions in TSC vote

kernelci.org/static/favicons/android-144x144.png, kernelci.org/static/favicons/android-192x192.png, kernelci.org/static/favicons/android-36x36.png, kernelci.org/static/favicons/android-48x48.png, kernelci.org/static/favicons/android-72x72.png, kernelci.org/static/favicons/android-96x96.png, kernelci.org/static/favicons/favicon-1024.png, kernelci.org/static/favicons/favicon-16x16.png, kernelci.org/static/favicons/favicon-256.png, kernelci.org/static/favicons/favicon-32x32.png, kernelci.org/static/favicons/favicon.ico
The KernelCI logo was designed to be with a white background but the PNG favicon files have a transparent background.  This poses some problems with dark themes as it make it hardly visible.
Update all the favicon PNG files with opaque white background.
=> kernelci.org: update favicon with white background

kernelci.org/content/en/docs/org/board.md
Remove myself (gtucker) from the list of Advisory Board members as I'm stepping down as TSC Chair.  This is effective on 2024-02-19 as previously agreed with the TSC at the end of 2023.
=> kernelci.org: remove gtucker as TSC Chair from board members

kernelci.org/content/en/docs/org/working-groups.md
Remove gtucker from the list of SysAdmin working group members. Related permissions and admin rights are in the process of being disabled or revoked accordingly.
=> kernelci.org: remove gtucker from SysAdmin working group

kernelci.org/content/en/docs/org/working-groups.md
Fix the date set on the working groups page (2024 instead of 2023, that was a typo).
Fixes: 00a84b06b2da ("kernelci.org: remove gtucker from SysAdmin working group")
=> kernelci.org: fix working groups page date

kernelci.org/content/en/blog/posts/2020/05/11/index.html, kernelci.org/content/en/blog/posts/2020/11/05/index.html, kernelci.org/content/en/blog/posts/2021/03/16/index.html, kernelci.org/content/en/blog/posts/2021/hackfests/index.md
Update all the stale links to the kernelci@groups.io archive in all the blog posts with corresponding ones to the new archive on lore.kernel.org.
=> kernelci.org: replace stale kernelci@groups.io links in blog

.github/ISSUE_TEMPLATE/new-tsc-member.md
Add a GitHub issue template to create a checklist used when adding a new member to Technical Steering Committee (TSC).
=> github: add issue template for new TSC members

kernelci.org/content/en/docs/org/tsc/_index.md
As I have updated my IRC nickname to `jenysadadia`, reflect the change in the TSC members' list.
=> tsc: update IRC nickname for Jeny

kernelci.org/content/en/docs/org/tsc/_index.md, kernelci.org/content/en/docs/org/tsc/votes.md
Add an entry to the TSC voting records for the 2024-03-14 monthly and add Shuah to the list of TSC members as this is effective on Monday 2024-03-18.
=> Add TSC voting record for 2024-03-14 and update docs accordingly

kernelci.org/content/en/docs/org/board.md
Add Nikolai Kondrashov (spbnick) to the list of voting board members as the new TSC Chair.  This is effective on 2024-04-01 as per the TSC vote on 2024-03-14.
=> kernelci.org: add spbnick as TSC Chair to board members

kernelci.org/content/en/docs/org/working-groups.md
Add Ricardo, who has been participating in the discussions and remove Guy, who hasn't been active.
=> kernelci.org: update members of the Web Dashboard WG

kernelci.org/content/en/docs/legacy/instances/chromeos/chromeos_changelog.md
Depend on https://github.com/kernelci/kernelci-core/pull/2199 and https://github.com/kernelci/kernelci-core/pull/2218
=> kernelci.org: legacy: chromeos: add new supported boards

kernelci.org/docker-compose.yaml
Add the Hugo -F option in docker-compose.yaml to also render pages with a publication date set in the future.
This is useful as the docker-compose setup uses the Hugo development server for previewing changes, not generating the static files served in a production deployment where only pages with a publication date in the past should be rendered.
=> kernelci.org: add -F option in docker-compose

kernelci.org/content/en/blog/posts/2024/strategic-updates/index.md
An update to the community in overdue. At the same time, a lot of project ground shift in direction with the new leadership that in place.
This article summarize many discussions that happened across different mediums over the past many weeks.
It is also intended to be a pre Open Source Summit update from th project.
=> kernelci.org: add blog with strategic update about the project

kernelci.org/content/en/docs/org/tsc/_index.md
Switch the preference from voting in meetings to voting by email, as members cannot attend a single meeting all at once.
=> tsc: Switch preference to voting by email

.github/workflows/deploy.yml
Initial hugo deployment over workflow
=> Add Hugo deployment over workflow

.github/workflows/deploy.yml
For correct deployment we need to strip 2 elements from path.
=> workflows/deploy: Strip 2 directories

kernelci.org/content/en/docs/org/maintainers.md
Remove gtucker from the list of maintainers for the GitHub kernelci org and Slack as per the TSC vote on 2024-05-13.
=> kernelci.org: update gtucker maintainer roles

.gitmodules, kernelci.org/content/en/docs/api, kernelci.org/content/en/docs/api_pipeline/_index.md, kernelci.org/content/en/docs/api_pipeline/api, kernelci.org/content/en/docs/api_pipeline/pipeline
Closes https://github.com/kernelci/kernelci-project/issues/338
Add `kernelci-pipeline` as a submodule to be able to include its documentation to `kernelci.org/external`.
=> Add kernelci-pipeline submodule

.github/workflows/deploy.yml
If we update also docsy, it will break hugo, as we are not using latest one.
=> workflows: Don't update all submodules

kernelci.org/config.toml
Let's just call it Foundation as "LF" fails to share enough context to the average visitor.
=> kernelci.org: make link to Foundation more meaningful

kernelci.org/config.toml, kernelci.org/content/en/_index.md, kernelci.org/content/en/blog/posts/2020/05/11/index.html, kernelci.org/content/en/blog/posts/2021/03/16/index.html, kernelci.org/content/en/blog/posts/2021/06/24/index.html, kernelci.org/content/en/org/board.md
Our foundation website is became our main kernelci.org website. So we can point there as 'Home´ and also drop the "foundation.' part of the urls.
=> docs: updates links after DNS switch

kernelci.org/content/en/labs/_index.md
As part of the refactor of the KernelCI documentation, in this step we create a new folder to host the overall context for KernelCI labs. It will point to the documentation on different ways to enable a lab in KernelCI Maestro.
=> docs: create a high level overview for Labs

kernelci.org/content/en/_index.md, kernelci.org/content/en/architecture/_index.md, kernelci.org/content/en/kernel-community/_index.md, kernelci.org/content/en/labs/_index.md
We have several types of audience; our documentation should reflect that. This PR is a initial step into creating a foundation to grow Documentation to our different types of users. You can see the proposed new users in the screenshot below.
Once we merge this, we can iterative improve the documentation (as it is being discussed in different forums).
this include the patch from #405 too.
=> New landing page for Documentation

kernelci.org/content/en/background.jpeg
We don't use it anymore in the new configuration.
=> docs: remove leftover background image

kernelci.org/content/en/kernel-community/_index.md
Add link to point to the documentation in the grafana dashboard.
=> docs: add link to documentation on visualize the results

.github/ISSUE_TEMPLATE/new-tsc-member.md, README.md, kernelci.org/content/en/admin/api.md, kernelci.org/content/en/admin/secrets.md, kernelci.org/content/en/blog/posts/2021/hackfests/index.md, kernelci.org/content/en/blog/posts/2022/sysadmin-onboard/index.md, kernelci.org/content/en/blog/posts/2023/api-early-access/index.md, kernelci.org/content/en/blog/posts/2023/api-timeline/index.md, kernelci.org/content/en/blog/posts/2023/fosdem-2023/index.md, kernelci.org/content/en/blog/posts/2023/rfp-ux-analysis-q-and-a/index.md, kernelci.org/content/en/blog/posts/2024/strategic-updates/index.md, kernelci.org/content/en/blog/posts/2024/tsc-updates/index.md, kernelci.org/content/en/faq.md, kernelci.org/content/en/legacy/_index.md, kernelci.org/content/en/legacy/contrib.md, kernelci.org/content/en/legacy/how-to.md, kernelci.org/content/en/legacy/instances/cip.md, kernelci.org/content/en/legacy/instances/local.md, kernelci.org/content/en/legacy/maintainers.md, kernelci.org/content/en/maestro/_index.md, kernelci.org/content/en/org/_index.md, kernelci.org/content/en/org/board.md, kernelci.org/content/en/org/maintainers.md, kernelci.org/content/en/org/tsc/_index.md, kernelci.org/content/en/org/working-groups.md
Since we moved the documentation domain to docs.kernelci.org we've left behind lots of broken links.
Hopefully this commit fixes them all!
=> docs: Fix lots of links

kernelci.org/content/en/kernel-community/view-results.md
In the `Evaluating Test Results` section, include link to KCIDB subscriber guide and remove KCIDB templates link. At the time of adding this doc, KCIDB subscriber guide didn't exist. Hence, update the links accordingly.
=> Kernel Community doc: add link to KCIDB subscriber guide

.github/ISSUE_TEMPLATE/api-staging-access.md, .github/ISSUE_TEMPLATE/new-tsc-member.md, kernelci.org/config.toml, kernelci.org/content/en/org/maintainers.md
According to TSC voting we are migrating to Discord. All links and content need to be updated accordingly.
=> upd(website): Update Slack to Discord

kernelci.org/content/en/maestro/_index.md
As we now have production instance deployed in place of early-access instance, update the documentation  accordingly.
=> Rename `Early-access` with `Production`

.github/workflows/deploy.yml
Many users get confused about /staging command and doesn't know where to expect website to appear. Fix that, so it will provide info when website got deployed, where it is deployed and caveats.
=> upd(workflows/deploy.yml): Add comment in issue about staging website

kernelci.org/content/en/contacts.md, kernelci.org/content/en/maestro/contrib.md
Reformat a bit, removing obsolete bits. Guidelines will need further work and improvements.
=> move(docs/contrib-guidelines): Add contrib guidelines to Maestro

kernelci.org/config.toml
Drop Legacy KernelCI link as that was killed already. And remove WIP mark from the dashboard.
=> menu: update to reflect current state

kernelci.org/content/en/org/maintainers.md, kernelci.org/content/en/org/tsc/votes.md
Add TSC voting records to transfer the `kernelci` PyPI package from `gtucker` to `nuclearcat` and add `arisut` as co-maintainer.
Update the Maintainers page accordingly and add missing entry about the PyPI `kci-dev` package.
=> PyPI ownership

kernelci.org/docker-hugo
The docker-hugo script isn't maintained and is now out of sync with docker-compose.yaml.  As such, remove it to avoid causing confusion about its purpose.
=> kernelci.org: remove obsolete docker-hugo script

kernelci.org/content/en/org/working-groups.md
Update membership to match the people who have been taking part in the discussions with Web development contractor team.
=> docs: update members of the Web Dashboard WG

kernelci.org/content/en/intro/monitor-tests.md
Our process is still quite elaborated, so we need a quick way out for simple request. So let's leave the option of Github request in our docs.
=> docs: Mention github issue to request tree addition

kernelci.org/content/en/intro/architecture/_index.md
That sentence was interrupted in the middle. Instead of trying to guess what it was supposed to say, delete it.
=> architecture: drop interrupted sentence
